name: ipyautoui-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
#  - http://10.10.30.125:8000
dependencies:
  - python>=3.7,<3.10
  - numpy
  - pandas
  - jupyterlab>=3.0.14
  - xeus-python
  - ipywidgets
  - ipyfilechooser
  - ipydatagrid
  - ipyvuetify
  - voila>=0.2.11
  - plotly
  - halo
  - jupytext
  - markdown
  - nodejs
  - altair
  - pydantic
  - dacite
  - xmltodict
  - pyyaml
  - openpyxl
  - black
  - nb_black
  - immutables
  - wcmatch
  - pytest
  - stringcase
  - pip
  - pip:
    - traitlets-paths